import axios from "axios";

export const FETCH_FRIEND_DATA_START = "FETCH_FRIEND_DATA_START";
export const FETCH_FRIEND_DATA_SUCCESS = "FETCH_FRIEND_DATA_SUCCESS";
export const FETCH_FRIEND_DATA_FAILURE = "FETCH_FRIEND_DATA_FAILURE";
